server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emazone
    username: ${username}
    password: ${password} #estos parametros se pasan por edit config, enviroment variables
  jpa:
    hibernate:
      ddl-auto: update